adobe/react-spectrum-charts

.github/workflows/sonarcloud.yml
=> fix: sonar cube when code is pushed to main

.github/workflows/publish-library.yml
=> build: update version in package.json when publishing

.github/workflows/sonarcloud.yml, README.md
Add the following to the README.md
- Table of Contents
- Overview
- Key Features:
- Installation
- npm
- yarn
- Usage
- Example
- Spectrum (Adobe Design System) Integration
- API
- Contributing
- License
- Apache License 2.0 Summary
- Roadmap
Need a detailed README for this project
Doc only. No tests
=> Setup README.md

CONTRIBUTING.md, README.md, rfcs/template.md
=> docs: update contribution guidelines

package.json, yarn.lock
=> switch to version of vega-lite that does not use structuredClone

.storybook/preview.tsx, src/stories/Chart.story.tsx, src/stories/ChartColors.story.tsx, src/stories/ChartExamples.story.tsx, src/stories/ChartHandles.story.tsx, src/stories/ChartStates.story.tsx, src/stories/ChartUnsafeVega.story.tsx, src/stories/components/Annotation/Annotation.story.tsx, src/stories/components/Area/Area.story.tsx, src/stories/components/Area/StackedArea.story.tsx, src/stories/components/Axis/Axis.story.tsx, src/stories/components/Axis/AxisReferenceLine.story.tsx, src/stories/components/AxisAnnotation/AxisAnnotation.story.tsx, src/stories/components/Bar/Bar.story.tsx, src/stories/components/Bar/DodgedBar.story.tsx, src/stories/components/Bar/ReferenceLineBar.story.tsx, src/stories/components/Bar/StackedBar.story.tsx, src/stories/components/Bar/TrellisBar.story.tsx, src/stories/components/ChartPopover/ChartPopover.story.tsx, src/stories/components/ChartTooltip/ChartTooltip.story.tsx, src/stories/components/Legend/Legend.story.tsx, src/stories/components/Legend/LegendHideShow.story.tsx, src/stories/components/Legend/LegendHighlight.story.tsx, src/stories/components/Legend/LegendSymbol.story.tsx, src/stories/components/Legend/legendHover.story.tsx, src/stories/components/Line/Line.story.tsx, src/stories/components/MetricRange/MetricRange.story.tsx, src/stories/components/Title/Title.story.tsx, src/stories/components/Trendline/Trendline.story.tsx
Just cleaning up the storybook experience
=> docs: remove placeholder description and set story height to auto

.github/workflows/publish-prod-storybook.yml
=> chore: [ issue30 ] update storybook to deploy to gh-pages branch

.github/workflows/publish-prod-storybook.yml
=> chore: update action, remove artifact deployment and remove node_modules

.github/workflows/pr-checks.yml, .github/workflows/publish-prod-storybook.yml, .storybook/manager.ts
=> chore: update action to build pr-specific storybooks

src/specBuilder/line/lineMarkUtils.ts, src/specBuilder/line/linePointUtils.test.ts, src/specBuilder/line/linePointUtils.ts, src/stories/components/Line/Line.story.tsx, src/stories/components/Line/Line.test.tsx
Add a selection ring around the selected point on a line.
Area and bar have a blue selection border. Add this to line for consistency.
Added tests and made sure existing ones are passing.
=> feat: selected point styling for line

.storybook/manager.ts
- Add a link to the PR that the storybook is built for 
- Change links to open in new tab
=> chore: cleanup PR-specific Storybook banner

src/hooks/useChartImperativeHandle.tsx, src/stories/Chart.test.tsx, src/stories/ChartHandles.story.tsx, src/types/Chart.ts
Add method to imperative handle for getting the base 64 png string
Needed for export to express
Added a test. Existing tests are passing.
=> feat: add getBase64Png method

.github/workflows/pr-comment.yml
=> add workflow for pr comments

src/specBuilder/trendline/trendlineUtils.ts, src/stories/components/Trendline/Trendline.story.tsx, src/stories/components/Trendline/Trendline.test.tsx
Normalized dimension work on trendlines broke moving averages. This adds the correct checks back in to fix these and adds tests to make sure that if they break again, it will be caught.
=> fix: moving averages were broken due to new normalized dimension work

src/Chart.tsx, src/components/EmptyState/EmptyState.tsx, src/index.ts, src/stories/ChartStates.story.tsx, src/stories/components/EmptyState/EmptyState.story.tsx, src/stories/components/EmptyState/EmptyState.test.tsx, src/types/Chart.ts
Exporting the existing component and adding a basic test.
Some consumers may want to use the empty state if they want to match the library design for cases where they aren't rendering inside of a `Chart` component.
=> feat: export empty state

src/Chart.tsx, src/components/BigNumber/BigNumber.css, src/components/BigNumber/BigNumber.tsx, src/specBuilder/chartSpecBuilder.ts, src/stories/components/BigNumber/BigNumber.story.tsx, src/stories/components/Line/Line.story.tsx, src/types/Chart.ts, src/utils/utils.ts
=> GTonkinson BigNumber

package.json, yarn.lock
=> Upgrade sb

src/Chart.tsx, src/components/BigNumber/BigNumber.tsx, src/specBuilder/chartSpecBuilder.ts, src/specBuilder/line/lineDataUtils.ts, src/specBuilder/line/lineSpecBuilder.ts, src/stories/components/BigNumber/BigNumber.story.tsx, src/stories/components/BigNumber/BigNumber.test.tsx, src/types/Chart.ts, src/utils/utils.ts
Method property for BigNumber
Added method attribute to BigNumberProps, calculate BigNumber's display value based on the method provided, tests for this as well as fixed tests for BigNumber's Chart.tsx implementation.
Added implementation to the Big-Number component
Jest tests written in BigNumber.test.tsx that pass.
- [X ] New feature (non-breaking change which adds functionality)
- [X ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X ] My code follows the code style of this project.
- [X ] My change requires a change to the documentation.
- [X ] I have updated the documentation accordingly.
- [X ] I have read the **CONTRIBUTING** document.
- [ X] I have added tests to cover my changes.
- [ X] All new and existing tests passed.
=> Nathaniel judd/byu team/big number

src/stories/components/BigNumber/BigNumber.test.tsx
Increase BigNumber coverage to 100% by testing untested stories
`yarn test`
=> test: increase BigNumber coverage to 100%

package.json, yarn.lock
=> upgrade storybook

src/types/Chart.ts
Add JSDocs
https://github.com/adobe/react-spectrum-charts/issues/32
=> chore: add jsdocs

.github/dependabot.yml
Add groups for stroybook and react so that they get updated together by dependabot
=> feat: add dependabot groups

plopfile.js, templates/component.hbs, templates/index.hbs, templates/story.hbs, templates/test.hbs
Need to update based on some recent refactoring
=> feat: update the plop generator

src/constants.ts, src/specBuilder/chartSpecBuilder.test.ts, src/specBuilder/chartSpecBuilder.ts, src/specBuilder/specUtils.ts
manual testing, for now
https://github.com/adobe/react-spectrum-charts/assets/20342122/f12d65d1-74f4-4c20-a8f4-33e28304058b
=> Add animation easing

src/constants.ts, src/specBuilder/bar/barSpecBuilder.test.ts, src/specBuilder/bar/barSpecBuilder.ts, src/specBuilder/bar/barTestUtils.ts, src/specBuilder/bar/barUtils.test.ts, src/specBuilder/bar/barUtils.ts, src/specBuilder/bar/dodgedBarUtils.test.ts, src/specBuilder/chartSpecBuilder.test.ts, src/specBuilder/chartSpecBuilder.ts, src/specBuilder/donut/donutSpecBuilder.test.ts, src/specBuilder/donut/donutSpecBuilder.ts, src/specBuilder/donut/donutUtils.test.ts, src/specBuilder/donut/donutUtils.ts, src/specBuilder/line/lineDataUtils.ts, src/specBuilder/line/lineSpecBuilder.test.ts, src/specBuilder/line/lineSpecBuilder.ts, src/specBuilder/scatter/scatterMarkUtils.test.ts, src/specBuilder/scatter/scatterMarkUtils.ts, src/specBuilder/scatter/scatterSpecBuilder.test.ts, src/specBuilder/scatter/scatterSpecBuilder.ts, src/specBuilder/signal/signalSpecBuilder.test.ts, src/specBuilder/signal/signalSpecBuilder.ts, src/specBuilder/specTestUtils.ts, src/specBuilder/trendline/trendlineDataUtils.ts, src/specBuilder/trendline/trendlineSignalUtils.test.ts, src/specBuilder/trendline/trendlineSignalUtils.ts
Refactor highlighted item to simplify the logic
=> Trendline display on hover refactor

.storybook/preview.tsx, src/stories/ChartExamples.story.tsx, src/stories/ChartHandles.story.tsx, src/stories/components/Line/Line.story.tsx
=> chore: add Storybook actions to chart callbacks

src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.story.tsx, src/stories/ChartExamples/FeatureMatrix/data.ts
Adds story `rsc-chart-examples--event-overlay-feature-matrix`
To provide a story with a scatter example of the excludeDataKeys functionality
https://github.com/adobe/react-spectrum-charts/assets/43940026/43da3113-9837-47f1-9817-a9b6347338d0
- [] I have added tests to cover my changes.
=> Add FeatureMatrix story to showcase excludeDataKeys

.storybook/main.ts, .storybook/preview.tsx, package.json, yarn.lock
=> chore: upgrade storybook

src/specBuilder/chartTooltip/chartTooltipUtils.test.ts, src/specBuilder/chartTooltip/chartTooltipUtils.ts, src/specBuilder/line/lineDataUtils.test.ts, src/specBuilder/line/lineDataUtils.ts, src/specBuilder/line/lineMarkUtils.test.ts, src/specBuilder/line/lineMarkUtils.ts, src/specBuilder/line/lineSpecBuilder.ts, src/specBuilder/line/lineUtils.ts, src/stories/components/ChartTooltip/HighlightBy.story.tsx, src/stories/components/ChartTooltip/HighlightBy.test.tsx, src/types/specBuilderTypes.ts
Add `highlightBy` support for line charts.
https://github.com/adobe/react-spectrum-charts/issues/238
ChartTooltip > HighlightBy > LineChart
=> An 334305/highlight by

src/specBuilder/legend/legendHighlightUtils.test.ts, src/specBuilder/legend/legendHighlightUtils.ts, src/specBuilder/legend/legendSpecBuilder.test.ts, src/specBuilder/legend/legendSpecBuilder.ts, src/specBuilder/legend/legendUtils.ts, src/specBuilder/signal/signalSpecBuilder.ts
Improve highlighting when using legend keys.
=> fix: improve legned prop keys to be more robust

src/RscChart.tsx, src/components/ChartPopover/ChartPopover.tsx, src/types/Chart.ts
Expose the RSP container padding for the popover.
=> feat: expose containerPadding for popover

src/constants.ts, src/specBuilder/axis/axisSpecBuilder.ts, src/specBuilder/bar/barSpecBuilder.ts, src/specBuilder/chartSpecBuilder.ts, src/specBuilder/donut/donutSpecBuilder.test.ts, src/specBuilder/donut/donutSpecBuilder.ts, src/specBuilder/donut/donutUtils.ts, src/specBuilder/legend/legendSpecBuilder.ts, src/specBuilder/signal/signalSpecBuilder.ts, src/specBuilder/specTestUtils.ts, src/stories/components/Donut/Donut.story.tsx, src/stories/components/Donut/Donut.test.tsx
https://github.com/adobe/react-spectrum-charts/issues/243
Want responsive implementations for all of our features.
Donut > Responsive
https://github.com/adobe/react-spectrum-charts/assets/40001449/4f9f9947-ff6e-4a81-b411-7eed4e64452b
=> feat: update font size calcs to be more responsive

src/constants.ts, src/specBuilder/bar/barAnnotationUtils.test.ts, src/specBuilder/bar/barAnnotationUtils.ts, src/specBuilder/bar/barSpecBuilder.test.ts, src/specBuilder/bar/barUtils.test.ts, src/specBuilder/bar/barUtils.ts, src/specBuilder/bar/dodgedBarUtils.test.ts, src/specBuilder/bar/dodgedBarUtils.ts, src/specBuilder/bar/stackedBarUtils.test.ts, src/specBuilder/bar/stackedBarUtils.ts, src/stories/components/Annotation/Annotation.story.tsx, src/stories/components/Annotation/Annotation.test.tsx, src/stories/components/Scatter/Scatter.story.tsx, src/stories/components/SegmentLabel/SegmentLabel.story.tsx, src/types/Chart.ts, src/types/specBuilderTypes.ts
Refactor bar annotations to break the logic up.
Fix annotations for horizontal bars.
#230 
Axis annotations where being hidden when it wasn't necessary.
Was able to refactor the spec so that it is less computationally intensive.
Bar > Annotation
=> Horizontal bar annotation

.github/workflows/pr-build.yml, .github/workflows/sonar.yml
=> build: new github actions to run sonar cloud on fork prs

.github/workflows/pr-build.yml, .github/workflows/sonar.yml
=> test: empty pr

.github/workflows/pr-build.yml, .github/workflows/sonar.yml
=> build: move storybook upload to post-build

.github/workflows/pr-build.yml, .github/workflows/sonar.yml
=> build: update how pr number is set

.github/workflows/pr-post-build.yml
=> Sonar cloud GitHub actions

.github/workflows/pr-sonar.yml
=> chore: fix conflict

src/RscChart.tsx, src/components/Annotation/Annotation.tsx, src/hooks/useLegend.tsx, src/specBuilder/axis/axisTrellisUtils.ts
=> chore: fix smells

src/alpha/components/Combo/Combo.tsx, src/specBuilder/combo/comboSpecBuilder.test.ts, src/specBuilder/combo/comboSpecBuilder.ts, src/stories/components/Combo/Combo.story.tsx, src/stories/components/Combo/Combo.test.tsx, src/types/Chart.ts
Adds `dimension` prop to Combo which is passed on to `Bar` and `Line`
<div>
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
```tsx
<Combo>
<Bar
dimension="datetime"
metric="people"
metricAxis="people" 
/>
<Line 
dimension="datetime"
metric="adoptionRate" 
metricAxis="adoption"
/>
</Combo>
```
</td>
<td>
```tsx
<Combo dimension="datetime">
<Bar 
metric="people"
metricAxis="people" 
/>
<Line 
metric="adoptionRate" 
metricAxis="adoption"
/>
</Combo>
```
</td>
</tr>
</table>
</div>
Provides a simpler API to set the common dimension of the Combo chart
- Passed existing tests
- Updated tests to cover changes
=> feat: Add dimension prop to Combo

.github/workflows/pr-sonar-test.yml
=> Sonar workflow

.github/workflows/pr-sonar-new.yml
=> test: new sonar workflow

.github/workflows/pr-sonar-new.yml
=> chore: cleanup

src/specBuilder/combo/comboSpecBuilder.ts, src/stories/components/Combo/Combo.story.tsx, src/stories/components/Combo/Combo.test.tsx, src/utils/utils.test.tsx, src/utils/utils.ts
Add story for `Combo` chart with tooltips on `Bar` and `Line` chart
Passed existing tests
Updated tests to cover changes
=> feat: Add Combo story with tooltip

src/expressionFunctions.test.ts, src/expressionFunctions.ts, src/specBuilder/axis/axisLabelUtils.test.ts, src/specBuilder/axis/axisLabelUtils.ts, src/stories/components/Axis/Axis.test.tsx
Switch the duration format so that it is automatic instead of based on granularity.
Cleaner API. How timestamps on youtube videos work.
Axis > DurationLabelFormat
=> Automatic duration formating

src/components/Line/Line.tsx, src/specBuilder/axis/axisSpecBuilder.ts, src/specBuilder/line/lineMarkUtils.ts, src/specBuilder/line/linePointUtils.ts, src/specBuilder/line/lineSpecBuilder.ts, src/specBuilder/line/lineUtils.ts, src/specBuilder/marks/markUtils.test.ts, src/specBuilder/marks/markUtils.ts, src/specBuilder/scale/scaleSpecBuilder.ts, src/stories/components/Combo/Combo.story.tsx, src/stories/components/Combo/Combo.test.tsx, src/stories/data/data.ts, src/types/Chart.ts
Support dual axes with different scales for `Combo` chart by adding metric axis option to `Line` chart
```jsx
<Combo dimension="datetime">
<Axis position="left" title="People" />
<Axis position="right" name="adoption" title="Adoption Rate" />
<Bar metric="people" />
<Line metric="adoptionRate" metricAxis="adoption" />
</Combo>
```
Allow dual axes with different scales in `Combo` chart
Passed existing tests
Updated tests to cover changes
=> feat: Support dual axes for Combo chart

src/stories/components/BigNumber/BigNumber.story.tsx
=> chore: Added sum and average stores to big number

src/VegaChart.tsx, src/index.ts
Export locales so that consumers can use/modify them.
Also switch to the [safer expression interpreter](https://vega.github.io/vega/usage/interpreter/)
=> Export locales

.eslintrc.cjs, src/locales/numberLocales/index.ts, src/locales/timeLocales/index.ts, src/utils/locale.test.ts, src/utils/locale.ts
Fix built exported types to avoid type errors.
=> Fix exported types

src/alpha/components/Bullet/Bullet.tsx, src/alpha/components/Bullet/index.ts, src/specBuilder/bullet/bulletSpecBuilder.test.ts, src/specBuilder/bullet/bulletSpecBuilder.ts, src/specBuilder/chartSpecBuilder.ts, src/specBuilder/combo/comboSpecBuilder.ts, src/stories/components/Bullet/Bullet.story.tsx, src/stories/components/Bullet/Bullet.test.tsx, src/stories/components/Bullet/data.ts, src/stories/components/Donut/Donut.story.tsx, src/types/Chart.ts, src/types/specBuilderTypes.ts, src/utils/utils.ts
Added a new bullet component
Ability to add a bullet chart and adjust the color and data of the chart itself. Right now only the ability to add one bar per component is included
N/A since we are using a different storyboard
Completes case A of the Bullet Chart Use Cases
Added tests in Bullet.test.tsx to check if all marks were created correctly and that the rect marks are filled with the right color.
Added tests in BulletSpecBuilder.test.ts to ensure that the Vega spec is being created correctly
=> Scrum 7/create component

src/constants.ts, src/specBuilder/bullet/bulletMarkUtils.test.ts, src/specBuilder/bullet/bulletMarkUtils.ts, src/specBuilder/bullet/bulletSpecBuilder.test.ts, src/specBuilder/bullet/bulletSpecBuilder.ts, src/stories/components/Bullet/Bullet.story.tsx, src/types/Chart.ts, src/types/specBuilderTypes.ts
=> Scrum 23/horizontal labeling v2

src/specBuilder/bullet/bulletDataUtils.test.ts, src/specBuilder/bullet/bulletDataUtils.ts, src/specBuilder/bullet/bulletMarkUtils.test.ts, src/specBuilder/bullet/bulletMarkUtils.ts, src/specBuilder/bullet/bulletSpecBuilder.ts, src/stories/components/Bullet/Bullet.story.tsx
This PR refactors the Bullet chart's data-building logic by updating `addData` function using Immer’s produce pattern.
- Creating `addData` to immutably update the data array.
- Adding `getBulletTransforms`, which dynamically adds the appropriate formula transforms.
- Introducing `getBulletTableData`, a utility to retrieve or create the required Vega data object.
General refactoring.
- Aligns Bullet with the same patterns used by Bar, Axis, and Donut.
- Makes the code easier to maintain and reason about.
- Supports future enhancements like richer transform pipelines and dynamic data injection with minimal change.
- Verified that Bullet charts still render correctly in Storybook.
- Confirmed that charts behave as expected with both default and flexible scale types.
- Ran full test suite …
=> Scrum 38/refactor/bullet data produce

src/specBuilder/bullet/bulletMarkUtils.test.ts, src/specBuilder/bullet/bulletMarkUtils.ts
=> Scrum 41/fix title bug

packages/react-spectrum-charts/src/Chart.tsx, packages/react-spectrum-charts/src/RscChart.tsx, packages/react-spectrum-charts/src/hooks/useChartHeight.tsx, packages/react-spectrum-charts/src/hooks/useChartImperativeHandle.tsx, packages/react-spectrum-charts/src/index.ts, packages/react-spectrum-charts/src/stories/Chart.test.tsx, packages/react-spectrum-charts/src/stories/ChartHandles.story.tsx, packages/react-spectrum-charts/src/types/chart.types.ts
Re export the vega-spec-builder
=> Re export vega spec builder

.gitignore, packages/react-spectrum-charts/src/hooks/useSpec.tsx, packages/vega-spec-builder/src/area/areaSpecBuilder.ts, packages/vega-spec-builder/src/axis/axisSpecBuilder.ts, packages/vega-spec-builder/src/bar/barSpecBuilder.ts, packages/vega-spec-builder/src/bullet/bulletSpecBuilder.ts, packages/vega-spec-builder/src/chartSpecBuilder.ts, packages/vega-spec-builder/src/combo/comboSpecBuilder.ts, packages/vega-spec-builder/src/donut/donutSpecBuilder.ts, packages/vega-spec-builder/src/legend/legendSpecBuilder.ts, packages/vega-spec-builder/src/line/lineSpecBuilder.ts, packages/vega-spec-builder/src/scatter/scatterSpecBuilder.ts, packages/vega-spec-builder/src/specUtils.ts, packages/vega-spec-builder/src/title/titleSpecBuilder.ts, packages/vega-spec-builder/src/types/specUtil.types.ts
=> restrict spec usermeta type with ScSpec

packages/react-spectrum-charts/src/Chart.tsx, packages/react-spectrum-charts/src/RscChart.tsx, packages/react-spectrum-charts/src/context/RscChartContext.tsx, packages/react-spectrum-charts/src/hooks/useChartInteractions.tsx, packages/react-spectrum-charts/src/hooks/useNewChartView.tsx, packages/react-spectrum-charts/src/hooks/usePopoverAnchorStyle.tsx, packages/react-spectrum-charts/src/hooks/useSpecProps.tsx, packages/react-spectrum-charts/src/hooks/useTooltipInteractions.tsx, packages/react-spectrum-charts/src/types/chart.types.ts, packages/react-spectrum-charts/src/utils/markClickUtils.ts
Refactor the RscChart component. It was too big and clunky to work in.
All tests are passing
=> refactor: clean up RscChart

packages/react-spectrum-charts/src/context/RscChartContext.tsx, packages/react-spectrum-charts/src/stories/components/Legend/LegendHideShow.story.tsx, packages/react-spectrum-charts/src/stories/components/Legend/LegendHideShow.test.tsx, packages/react-spectrum-charts/src/utils/markClickUtils.test.ts, packages/react-spectrum-charts/src/utils/markClickUtils.ts
Right clicking on a legend item was triggering the hide/show and onClick for that legend item. This PR fixes this behavior.
Existing tests are passing. New tests added.
=> Fix hide show right click

packages/react-spectrum-charts/src/stories/components/Axis/Axis.story.tsx, packages/react-spectrum-charts/src/stories/components/Axis/Axis.test.tsx, packages/react-spectrum-charts/src/stories/components/Axis/timeData.json, packages/vega-spec-builder/src/axis/axisLabelUtils.ts, packages/vega-spec-builder/src/types/axis/axisSpec.types.ts
Enable year granularity for axis.
=> Axis year granularity

packages/react-spectrum-charts/src/stories/components/Axis/Axis.test.tsx, packages/vega-spec-builder/src/axis/axisLabelUtils.ts
=> feat: switch primary label for second granularity to minutes

packages/react-spectrum-charts/src/hooks/useSpec.tsx, packages/vega-spec-builder/src/chartSpecBuilder.test.ts, packages/vega-spec-builder/src/chartSpecBuilder.ts
Clone the spec before returning it so that it is not "read only"
=> Clone built spec

package.json, plopfile.js, templates/package/LICENSE.hbs, templates/package/README.md.hbs, templates/package/index.ts.hbs, templates/package/package-react.json.hbs, templates/package/package.json.hbs, templates/package/src-index.ts.hbs, templates/package/tsconfig.json.hbs, templates/package/webpack-react.config.js.hbs, templates/package/webpack.config.js.hbs
Creating packages won't be common, but having a plop generator will help keep webpack, tsconfigs, etc.. consistent without needing to copy manually.
Features:
- Generates common configs used for packages
- Options for adding react dependencies and dependencies for the other main packages in the monorepo
- Dynamically grabs package versions from the root config files
This is devtooling so testing requirements are limited.
Manual validation to make sure everything generates as expected and packages build using each option.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
=> Package generator

packages/constants/constants.ts, packages/vega-spec-builder/src/area/areaSpecBuilder.test.ts, packages/vega-spec-builder/src/area/areaSpecBuilder.ts, packages/vega-spec-builder/src/area/areaUtils.ts, packages/vega-spec-builder/src/bar/dodgedBarUtils.test.ts, packages/vega-spec-builder/src/chartSpecBuilder.test.ts, packages/vega-spec-builder/src/chartSpecBuilder.ts, packages/vega-spec-builder/src/chartTooltip/chartTooltipUtils.test.ts, packages/vega-spec-builder/src/chartTooltip/chartTooltipUtils.ts, packages/vega-spec-builder/src/legend/legendHighlightUtils.ts, packages/vega-spec-builder/src/legend/legendUtils.ts, packages/vega-spec-builder/src/line/lineDataUtils.ts, packages/vega-spec-builder/src/line/lineMarkUtils.test.ts, packages/vega-spec-builder/src/line/lineMarkUtils.ts, packages/vega-spec-builder/src/marks/markUtils.test.ts, packages/vega-spec-builder/src/marks/markUtils.ts, packages/vega-spec-builder/src/metricRange/metricRangeUtils.ts, packages/vega-spec-builder/src/scatter/scatterMarkUtils.test.ts, packages/vega-spec-builder/src/scatter/scatterMarkUtils.ts, packages/vega-spec-builder/src/scatterPath/scatterPathUtils.ts, packages/vega-spec-builder/src/specTestUtils.ts, packages/vega-spec-builder/src/trendline/trendlineDataUtils.ts, packages/vega-spec-builder/src/trendline/trendlineSignalUtils.test.ts
Just changing `highlightedItem` to `controlledHighlightedItem` and `highlightedSeries` to `controlledHighlightedSeries`
=> refactor: update controlled signal names
