adobe/react-spectrum-charts

- src/Prism.tsx
- src/hooks/usePrismImperativeHandle.tsx
- src/stories/Prism.test.tsx
- src/utils/utils.test.tsx
- src/utils/utils.ts
When exporting a PNG and providing a custom filename for the export, Chinese characters get turned in to non-sense.
[Filename passed in to download function gets messed up in Chinese](https://github.com/adobe/react-spectrum-charts/issues/7)
This is causing internationalization problems.
`yarn pack-test`
Then installed the tarball in product to verify issue was fixed.
> fix: do not use snake case on potentially localized values

- __mocks__/useElementSize.ts
- jest.config.js
- package.json
- src/Chart.tsx
- src/VegaChart.tsx
- src/VegaRenderer.tsx
- src/hooks/useChartWidth.tsx
- src/stories/Chart.test.tsx
- src/stories/ChartExamples.story.tsx
- src/stories/ChartUnsafeVega.story.tsx
- src/stories/components/Title/Title.test.tsx
- yarn.lock
Currently the library uses a tool called react-vega to render the vega charts. The issue with react-vega is we get some weird behavior like resize flicker and a lot of console.errors and console.warns.
Going one level lower to vega-embed and controlling the lifecycle ourselves solves these issues.
All tests are passing which confirms that the new vega renderer was swapped out successfully.
> Switch to vega embed

- README.md
- __mocks__/useElementSize.ts
- jest.config.js
- package.json
- src/Chart.tsx
- src/VegaChart.tsx
- src/expressionFunctions.ts
- src/hooks/useElementSize.tsx
- yarn.lock
vega and vega-lite were listed as dependencies. The issue with this is it is likely that users of this library will have multiple instances installed of vega/vega-lite and all the associated packages. This is not only bad for size of installed packages, it can cause RSC to fail to render because some of the vega packages are persistent instances. For example, vega-functions us used to register custom expression functions. If the functions is registered to one instance but vega tries to digest the functions from the other instance, the registered function won't exist.
see description
Ran `yarn pack-test` and installed into APA where the multiple install issue was reported from. Confirmed that it is fixed.
> Fix vega dependencies

- src/specBuilder/area/areaSpecBuilder.test.ts
- src/specBuilder/area/areaSpecBuilder.ts
- src/specBuilder/bar/barUtils.test.ts
- src/specBuilder/bar/barUtils.ts
- src/specBuilder/legend/legendHighlightUtils.test.ts
- src/specBuilder/legend/legendHighlightUtils.ts
- src/specBuilder/legend/legendTestUtils.ts
- src/specBuilder/line/lineSpecBuilder.test.ts
- src/specBuilder/line/lineSpecBuilder.ts
- src/specBuilder/line/lineUtils.test.ts
- src/specBuilder/line/lineUtils.ts
- src/specBuilder/marks/markUtils.test.ts
- src/specBuilder/marks/markUtils.ts
- src/specBuilder/metricRange/metricRangeUtils.test.ts
- src/specBuilder/metricRange/metricRangeUtils.ts
- src/specBuilder/signal/signalSpecBuilder.test.ts
- src/specBuilder/signal/signalSpecBuilder.ts
- src/specBuilder/trendline/trendlineUtils.test.ts
- src/specBuilder/trendline/trendlineUtils.ts
- src/stories/components/ChartPopover/ChartPopover.test.tsx
- src/stories/components/Line/Line.test.tsx
- src/stories/components/Trendline/Trendline.story.tsx
- src/stories/components/Trendline/Trendline.test.tsx
- src/types/specBuilderTypes.ts
When you hover or select a line, the other series lines did not change in opacity. On the other hand, for bar and area, as you hover or select different areas/bars, they get highlighted by all other areas/bars dropping in opacity by 1/5th.
This PR updates line so that it behaves the same way as area and bar on hover/select.
Standardization in behavior across chart types.
All existing tests are passing or were updated to reflect the new behavior.
Unit tests were added to test the spec is as expected
Tests were written for the new stories and existing stories to validate behavior
> feat: lines get highlighted with hover and select interactions

- src/components/Bar/Bar.tsx
- src/specBuilder/bar/barSpecBuilder.test.ts
- src/specBuilder/bar/barSpecBuilder.ts
- src/specBuilder/bar/barTestUtils.ts
- src/specBuilder/bar/trellisedBarUtils.test.ts
- src/specBuilder/bar/trellisedBarUtils.ts
- src/stories/components/Bar/TrellisBar.story.tsx
- src/stories/components/Bar/TrellisBar.test.tsx
- src/types/Chart.ts
- src/types/specBuilderTypes.ts
Allows users to increase or decrease padding between charts in a trellis.
Makes it easier to avoid charts crashing into each other.
> Expose trellis padding in Bar Props

- package.json
- src/specBuilder/area/areaSpecBuilder.ts
- src/specBuilder/axis/axisSpecBuilder.ts
- src/specBuilder/bar/barSpecBuilder.ts
- src/specBuilder/chartSpecBuilder.ts
- src/specBuilder/data/dataUtils.ts
- src/specBuilder/legend/legendSpecBuilder.ts
- src/specBuilder/line/lineSpecBuilder.ts
- src/specBuilder/scale/scaleSpecBuilder.ts
- src/specBuilder/title/titleSpecBuilder.tsx
- yarn.lock
We were using `version_number - latest` syntax for the dependency and peer dependency ranges. This did not seem to be working as expected so this switches to use `>= version_number`.
https://github.com/adobe/react-spectrum-charts/issues/34
Multiple versions of packages were being installed for comsumers
1. Created a new app from scratch using v18
2. Reproduced the reported error
3. Made updates
4. `yarn pack-test`
5. installed locally built package
6. confirmed it all works as expected
> Update dependency ranges

- src/Chart.css
- src/Chart.tsx
- src/constants.ts
- src/hooks/useSpec.tsx
- src/specBuilder/chartSpecBuilder.test.ts
- src/specBuilder/chartSpecBuilder.ts
- src/specBuilder/specUtils.ts
- src/stories/Chart.story.tsx
- src/stories/Chart.test.tsx
- src/themes/spectrumTheme.ts
- src/types/Chart.ts
the backgroundColor prop existed but it didn't update the color of the spectrum wrapper. Also it didn't set the color on the actual svg so when you copy or download the chart, that background color would not persist.
backgroundColor wasn't fully supported
Added tests to ensure the color gets set in all the right places
> feat: set backgroundColor on chart

- src/Chart.tsx
- src/stories/components/Legend/Legend.test.tsx
We should use the `legendEntries` scale to match `descriptions` with the appropriate legend entry. 
You can see that descriptions still work after this change by viewing the legend descriptions story and hovering over a legend entry: https://opensource.adobe.com/react-spectrum-charts/PR-44/?path=/story/rsc-legend--descriptions
It's possible to have a chart with multiple legend entries but only one series. If we match descriptions using series (color), it won't be possible to have descriptions for these types of charts. Matching based on legend entries resolves the issue.
> fix: use legendEntries scale for description matching

- src/Chart.tsx
- src/hooks/useChartImperativeHandle.tsx
- src/stories/Chart.test.tsx
- src/stories/ChartHandles.story.tsx
- src/types/Chart.ts
Add a `getSvg()` method that returns the svg string for the chart.
This will be helpful for the figma plugin since it needs the SVG string to pass into the figma API
Added tests and stories
> feat: add getSvg handle

- package.json
- yarn.lock
This PR only adds a dependency in package.json which is a requirement for RSC but wasn't listed. 
It all started with a bug in CJA where custom tooltip wouldn't work after upgrading to the latest alpha (alpha-12). After a bit of digging I found out:
* tag v0.0.1-alpha.10 is where the tooltip stops working for me, alpha.9 is ok
* if I comment (in alpha.10) src/Chart.tsx lines 287 through 305, the issue goes away
List the package `vega-tooltip` as a dependency since it is a requirement for custom tooltips. The custom tooltip support was added in `vega-tooltip v0.26.0`. For the CJA bug, @quarry/react-vega (a dep of CJA) has vega-tooltip@0.19.0 which explains why the custom tooltip wouldn't work. The solution was to add `vega-tooltip` to resolutions.
Adding vega-tooltip as a dependency will …
> fix: enforce minimum vega-tooltip for custom tooltips

- src/specBuilder/scatter/scatterSpecBuilder.test.ts
- src/specBuilder/scatter/scatterSpecBuilder.ts
For light mode, scatter uses the `multiply` blend mode but this doesn't work in dark mode. The reason is, `multiply` always darkens the given color.
Instead we need to use `screen` blend mode when in dark mode.
https://github.com/adobe/react-spectrum-charts/issues/50
Need to support light and dark mode for all features
Added tests to make sure correct blend mode is set.
https://github.com/adobe/react-spectrum-charts/assets/40001449/e47445ef-f5e5-443b-ad5e-0ba38317c2a5
> feat: use screen blend mode in dark mode

- src/Chart.tsx
- src/components/Scatter/Scatter.tsx
- src/hooks/useSpec.tsx
- src/specBuilder/chartSpecBuilder.test.ts
- src/specBuilder/chartSpecBuilder.ts
- src/specBuilder/legend/legendFacetUtils.test.ts
- src/specBuilder/legend/legendFacetUtils.ts
- src/specBuilder/legend/legendHighlightUtils.test.ts
- src/specBuilder/legend/legendHighlightUtils.ts
- src/specBuilder/legend/legendSpecBuilder.test.ts
- src/specBuilder/legend/legendSpecBuilder.ts
- src/specBuilder/legend/legendUtils.test.ts
- src/specBuilder/legend/legendUtils.ts
- src/specBuilder/scatter/scatterSpecBuilder.test.ts
- src/specBuilder/scatter/scatterSpecBuilder.ts
- src/specBuilder/signal/signalSpecBuilder.test.ts
- src/specBuilder/signal/signalSpecBuilder.ts
- src/stories/components/Scatter/Scatter.story.tsx
- src/stories/components/Scatter/Scatter.test.tsx
- src/themes/spectrumTheme.ts
- src/types/Chart.ts
Need to be able to support continuous data in legends. This PR adds that support and makes it possible to use size as a facet for scatter plots.
Scatter > *
https://github.com/adobe/react-spectrum-charts/issues/50
Scatter needs to be able to support size as a facet
All existing tests pass and new tests were added
> feat: continuous data in legends and multiple legends

- package.json
Use `cross-env` for `yarn storybook` so it runs out-of-the-box on Windows.
Bug report here: https://github.com/adobe/react-spectrum-charts/issues/85
A Windows developer is interested in contributing to this project, but found that any command using `export` needed `setx` instead of `export`.
Manual testing on Windows and Mac machines
Windows works out of the box:
No changes to Mac function:
> fix: use cross-env for storybook

- src/expressionFunctions.test.ts
- src/expressionFunctions.ts
- src/specBuilder/axis/axisLabelUtils.test.ts
- src/specBuilder/axis/axisLabelUtils.ts
- src/specBuilder/axis/axisUtils.ts
- src/specBuilder/bar/barTestUtils.ts
- src/specBuilder/bar/barUtils.test.ts
- src/specBuilder/bar/barUtils.ts
- src/stories/components/Axis/Axis.story.tsx
- src/stories/components/Axis/Axis.test.tsx
- src/stories/components/Bar/data.ts
- src/themes/spectrumTheme.ts
- src/types/Chart.ts
Add ability to set labels to truncate if they are too long instead of hiding them
https://github.com/adobe/react-spectrum-charts/issues/84
Sometimes it is preferable to have the axis labels truncate instead of hide
Existing tests pass. New tests pass.
> feat: truncateLabels on Axis

- src/components/Scatter/Scatter.tsx
- src/specBuilder/scatter/scatterSpecBuilder.test.ts
- src/specBuilder/scatter/scatterSpecBuilder.ts
- src/stories/components/Scatter/Scatter.story.tsx
- src/stories/components/Scatter/Scatter.test.tsx
- src/types/Chart.ts
- src/types/specBuilderTypes.ts
Support `lineType`, `lineWidth`, and `opacity` as facets for scatter data.
These are supported on other chart types.
- Scatter > Line Type
- Scatter > Opacity
Line Type:
Opacity:
> feat: support opacity, lineType and lineWidth facets for scatter

- src/Chart.tsx
- src/RscChart.tsx
- src/types/Chart.ts
- src/utils/utils.ts
`Chart.tsx` has become large and a little bit difficult to work with. Breaking out the Vega chart into a separate component 
`Chart.tsx` has become large and a little bit difficult to work with. Breaking out the Vega chart into a separate component will make maintenance and feature work easier. 
This will also make it easier for us to add and manage components that aren't pure Vega components, such as Big Number (React component).  
Test suite passes. I did a manual review of our Storybook components. I viewed most chart types and paid close attention to logic that isn't built into the spec: empty state, tooltip, popover.
> chore: move the vega chart to its own file

- src/components/BigNumber/bigNumberFormatUtils.ts
Remove unnecessary handling of default formatter in bigNumberFormatUtils.
Remove unnecessary code that doesn't affect test or storybook output.
Exisiting Number Format tests still pass.  Some other BigNumber tests fail due to an unrelated issue that is unaffected by this change.
> Remove unnecessary code from bigNumberFormatUtils

- src/specBuilder/legend/legendUtils.test.ts
- src/specBuilder/legend/legendUtils.ts
- src/stories/ChartExamples.test.tsx
In the recent multiple legend work, there was a regression where the fill opacity of legend symbols with highlight enabled wasn't working correctly.
Added test that replicates the broken state. That test and all others pass.
before:
after:
> fix: symbol fill opacity wasn't working with highlight enabled

- src/specBuilder/chartSpecBuilder.test.ts
- src/specBuilder/chartSpecBuilder.ts
- src/stories/Chart.story.tsx
> feat: add timer value to signals

- src/specBuilder/line/lineMarkUtils.ts
- src/specBuilder/marks/markUtils.ts
- src/specBuilder/scatter/scatterMarkUtils.test.ts
- src/specBuilder/scatter/scatterMarkUtils.ts
- src/specBuilder/scatter/scatterSpecBuilder.test.ts
- src/specBuilder/scatter/scatterSpecBuilder.ts
- src/specBuilder/scatter/scatterTestUtils.ts
- src/stories/components/Scatter/Scatter.story.tsx
- src/stories/components/Scatter/Scatter.test.tsx
- src/utils/utils.ts
Basic scatter plot tooltip support. This is only the logic for displaying the tooltip. This does not include any logic for highlighting.
[Scatter Plot](https://github.com/adobe/react-spectrum-charts/issues/50)
Tooltips are fundamental and should be supported on all standard mark types
Existing tests pass, new tests added.
> An 338345/scatter tooltip

- src/constants.ts
- src/specBuilder/marks/markUtils.ts
- src/specBuilder/scatter/scatterMarkUtils.test.ts
- src/specBuilder/scatter/scatterMarkUtils.ts
- src/specBuilder/scatter/scatterSpecBuilder.test.ts
- src/specBuilder/scatter/scatterSpecBuilder.ts
- src/stories/components/Scatter/Scatter.story.tsx
- src/stories/components/Scatter/Scatter.test.tsx
Add highlighting to scatter points when the tooltip is visible
[Scatter plot](https://github.com/adobe/react-spectrum-charts/pull/129#:~:text=Related%20Issue-,Scatter%20Plot,-Motivation%20and%20Context)
Highlighting helps convey which point the tooltip is for
Added tests. All existing tests are passing.
https://github.com/adobe/react-spectrum-charts/assets/40001449/4b7adab4-2408-4c40-b436-0f7634c653b2
Scatter > Tooltip
> feat: tooltip point highlighting on scatter

- src/specBuilder/marks/markUtils.ts
- src/specBuilder/scatter/scatterMarkUtils.test.ts
- src/specBuilder/scatter/scatterMarkUtils.ts
- src/specBuilder/scatter/scatterSpecBuilder.test.ts
- src/specBuilder/scatter/scatterSpecBuilder.ts
- src/stories/components/Scatter/Scatter.story.tsx
- src/stories/components/Scatter/Scatter.test.tsx
Scatter plot popover support.
[Scatter Plot](https://github.com/adobe/react-spectrum-charts/issues/50)
Popovers are fundamental and should be supported on all standard mark types
Existing tests pass, new tests added.
> feat: popovers for scatter plot

- src/constants.ts
- src/specBuilder/chartSpecBuilder.test.ts
- src/specBuilder/chartSpecBuilder.ts
- src/specBuilder/legend/legendFacetUtils.ts
- src/specBuilder/legend/legendSpecBuilder.test.ts
- src/specBuilder/legend/legendSpecBuilder.ts
- src/specBuilder/legend/legendUtils.ts
- src/specBuilder/marks/markUtils.test.ts
- src/specBuilder/marks/markUtils.ts
- src/specBuilder/scale/scaleSpecBuilder.ts
- src/specBuilder/scatter/scatterMarkUtils.ts
- src/specBuilder/scatter/scatterSpecBuilder.test.ts
- src/specBuilder/scatter/scatterSpecBuilder.ts
- src/stories/components/Scatter/Scatter.story.tsx
- src/stories/components/Scatter/Scatter.test.tsx
- src/types/Chart.ts
Support linear color scales. This allows the color of a given scatter mark to be determined by a linear color scale instead of an ordinal one.
https://github.com/adobe/react-spectrum-charts/issues/50
Linear color scales is something that has been requested and will likely be needed by some for scatter plot.
Scatter > ColorScaleType
> feat: support linear color scales for scatter

- src/specBuilder/scatter/scatterSpecBuilder.test.ts
- src/specBuilder/scatter/scatterSpecBuilder.ts
- src/specBuilder/trendline/trendlineSignalUtils.test.ts
- src/specBuilder/trendline/trendlineSignalUtils.ts
- src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.story.tsx
- src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.test.tsx
Add necessary signal so that display on hover works for scatter plot trendlines.
[Scatter plot](https://github.com/adobe/react-spectrum-charts/issues/50)
displayOnHover should work for all marks that support trendlines
Chart > Examples > MultipleSegmentFeatureMatrix
https://github.com/adobe/react-spectrum-charts/assets/40001449/cfc2ec8b-9a2b-4296-b22c-8c1922e16ce5
> feat: support displayOnHover for scatter trendlines

- src/specBuilder/line/lineSpecBuilder.test.ts
- src/specBuilder/marks/markUtils.ts
- src/specBuilder/trendline/trendlineDataTransformUtils.test.ts
- src/specBuilder/trendline/trendlineDataTransformUtils.ts
- src/specBuilder/trendline/trendlineDataUtils.test.ts
- src/specBuilder/trendline/trendlineDataUtils.ts
- src/specBuilder/trendline/trendlineMarkUtils.test.ts
- src/specBuilder/trendline/trendlineMarkUtils.ts
- src/specBuilder/trendline/trendlineScaleUtils.ts
- src/specBuilder/trendline/trendlineSignalUtils.ts
- src/specBuilder/trendline/trendlineTestUtils.ts
- src/specBuilder/trendline/trendlineUtils.test.ts
- src/specBuilder/trendline/trendlineUtils.ts
- src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.story.tsx
- src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.test.tsx
- src/stories/components/Trendline/Trendline.story.tsx
- src/stories/components/Trendline/Trendline.test.tsx
- src/types/Chart.ts
- src/types/specBuilderTypes.ts
Add `orientation` to `Trendline`. This allows you to flip the dimension and metric if desired.
The main advantage of this feature is it allows for vertical average and median lines on scatter plots.
Trendline > Orientation
Chart > Examples > FeatureMatrix
Chart > Examples > MultipleSegmentFeatureMatrix
> feat: support 'orientation' for trendline

- src/components/TrendlineAnnotation/TrendlineAnnotation.tsx
- src/components/TrendlineAnnotation/index.ts
- src/specBuilder/trendline/trendlineDataTransformUtils.test.ts
- src/specBuilder/trendline/trendlineDataTransformUtils.ts
- src/specBuilder/trendline/trendlineDataUtils.ts
- src/specBuilder/trendline/trendlineMarkUtils.test.ts
- src/specBuilder/trendline/trendlineMarkUtils.ts
- src/specBuilder/trendline/trendlineTestUtils.ts
- src/specBuilder/trendline/trendlineUtils.ts
- src/specBuilder/trendlineAnnotation/index.ts
- src/specBuilder/trendlineAnnotation/trendlineAnnotationUtils.test.ts
- src/specBuilder/trendlineAnnotation/trendlineAnnotationUtils.ts
- src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.story.tsx
- src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.test.tsx
- src/stories/components/TrendlineAnnotation/TrendlineAnnotation.story.tsx
- src/stories/components/TrendlineAnnotation/TrendlineAnnotation.test.tsx
- src/types/Chart.ts
- src/types/specBuilderTypes.ts
Add a new `TrendlineAnnotation` component that will add annotations to a `Trendline`. This supports `TrendlineAnnotation` for aggregate trendlines (average, median).
The following props are supported:
- dimensionValue
- numberFormat
- prefix
Adding annotations to trendlines allows for more context and information.
- Chart > Examples > FeatureMatrix
- Trendline > TrendlineAnnotation > *
Existing and new tests all pass
> An 341517/trendline annotation

- jest.config.js
- package.json
- src/VegaChart.tsx
- src/expressionFunctions.test.ts
- src/expressionFunctions.ts
- src/locales/numberLocales/index.ts
- src/locales/timeLocales/index.ts
- src/specBuilder/axis/axisLabelUtils.test.ts
- src/specBuilder/axis/axisLabelUtils.ts
- src/stories/components/Axis/Axis.story.tsx
- src/stories/components/Axis/Axis.test.tsx
- src/types/Chart.ts
- src/utils/locale.ts
- yarn.lock
Add `duration` as an option for labelFormat. This will display seconds as HH:MM:SS.
example:
- `60 = 00:01:00`
- `3600 = 01:00:00`
- `3603661 = 1,001:01:01`
Axis > DurationLabelFormat
> Support duration label format

- src/Chart.tsx
- src/specBuilder/area/areaSpecBuilder.test.ts
- src/specBuilder/area/areaUtils.test.ts
- src/specBuilder/area/areaUtils.ts
- src/specBuilder/bar/barSpecBuilder.test.ts
- src/specBuilder/bar/barTestUtils.ts
- src/specBuilder/bar/barUtils.test.ts
- src/specBuilder/bar/barUtils.ts
- src/specBuilder/bar/dodgedBarUtils.test.ts
- src/specBuilder/bar/stackedBarUtils.test.ts
- src/specBuilder/bar/stackedBarUtils.ts
- src/specBuilder/line/lineMarkUtils.ts
- src/specBuilder/line/linePointUtils.ts
- src/specBuilder/line/lineSpecBuilder.test.ts
- src/specBuilder/line/lineTestUtils.ts
- src/specBuilder/metricRange/metricRangeUtils.test.ts
- src/specBuilder/metricRange/metricRangeUtils.ts
Fixes almost all tests broken by animations feature
Allows us to keep existing test suite while adding animations.  Note that one functional test (Trellised Dodged bar) is failing and unaffected by these test changes.
yarn test
> Add animation spec backwards compatibility with existing tests

- src/components/TrendlineAnnotation/TrendlineAnnotation.tsx
- src/specBuilder/marks/markUtils.test.ts
- src/specBuilder/marks/markUtils.ts
- src/specBuilder/trendline/trendlineMarkUtils.test.ts
- src/specBuilder/trendline/trendlineMarkUtils.ts
- src/specBuilder/trendline/trendlineTestUtils.ts
- src/specBuilder/trendline/trendlineUtils.test.ts
- src/specBuilder/trendline/trendlineUtils.ts
- src/specBuilder/trendlineAnnotation/trendlineAnnotationUtils.test.ts
- src/specBuilder/trendlineAnnotation/trendlineAnnotationUtils.ts
- src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.story.tsx
- src/stories/components/Trendline/Trendline.test.tsx
- src/stories/components/TrendlineAnnotation/TrendlineAnnotation.story.tsx
- src/stories/components/TrendlineAnnotation/TrendlineAnnotation.test.tsx
- src/types/Chart.ts
- src/types/specBuilderTypes.ts
Add `badge` prop to `TrendlineAnnotation`. This will display the annotation as a badge where the color of the badge matches the trendline color.
This is good for when you want to ensure readability of the annotation or when you want the color of the badge to help indicate which line it is for.
- Trendline > TrendlineAnnotation > Badge
- Trendline > TrendlineAnnotation > Supreme
- Chart > Examples > MultipleSegmentFeatureMatrix
> feat: trendline annotation badge

- src/components/ScatterPath/ScatterPath.tsx
- src/components/ScatterPath/index.ts
- src/components/index.ts
- src/constants.ts
- src/specBuilder/chartSpecBuilder.ts
- src/specBuilder/legend/legendHighlightUtils.test.ts
- src/specBuilder/legend/legendHighlightUtils.ts
- src/specBuilder/legend/legendTestUtils.ts
- src/specBuilder/legend/legendUtils.ts
- src/specBuilder/line/lineUtils.ts
- src/specBuilder/scatter/scatterMarkUtils.ts
- src/specBuilder/scatter/scatterSpecBuilder.ts
- src/specBuilder/scatterPath/index.ts
- src/specBuilder/scatterPath/scatterPathUtils.test.ts
- src/specBuilder/scatterPath/scatterPathUtils.ts
- src/specBuilder/specUtils.ts
- src/specBuilder/trendlineAnnotation/trendlineAnnotationUtils.test.ts
- src/specBuilder/trendlineAnnotation/trendlineAnnotationUtils.ts
- src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.story.tsx
- src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.test.tsx
- src/stories/ChartExamples/FeatureMatrix/data.ts
- src/stories/components/ScatterPath/ScatterPath.story.tsx
- src/stories/components/ScatterPath/ScatterPath.test.tsx
- src/types/Chart.ts
- src/types/specBuilderTypes.ts
Adds a new advanced scatter component called `<ScatterPath/>`. This can be used to draw paths that connect points based off some grouping.
Supported features:
* `color`
* `groupBy`
* `opacity`
* `pathWidth`
* Can vary at each connecting point
Need to be able to show a visual connection between points on a scatter plot
Chart > Examples > TimeCompareFeatureMatrix
Scatter > ScatterPath > *
> An 340716/scatter path

- src/specBuilder/axis/axisLabelUtils.test.ts
- src/specBuilder/axis/axisLabelUtils.ts
- src/stories/components/Axis/Axis.test.tsx
Currency values under $1000 were not displayed as currency when using `shortCurrency`. This fixes that.
> fix: short currency wasn't displaying as currency under

- src/constants.ts
- src/specBuilder/chartSpecBuilder.test.ts
- src/specBuilder/chartSpecBuilder.ts
Increase animation duration according to feedback.  Also refactor timer magic numbers into constants.
All tests related to this feature pass.  One Trellis bar test fails due to unrelated error
https://github.com/adobe/react-spectrum-charts/assets/20342122/5d53451e-50b1-488c-8387-043179d5133b
> Change animation duration

- src/components/ChartTooltip/ChartTooltip.tsx
- src/specBuilder/area/areaSpecBuilder.test.ts
- src/specBuilder/area/areaSpecBuilder.ts
- src/specBuilder/bar/barSpecBuilder.test.ts
- src/specBuilder/bar/barSpecBuilder.ts
- src/specBuilder/data/dataUtils.ts
- src/specBuilder/donut/donutSpecBuilder.test.ts
- src/specBuilder/donut/donutSpecBuilder.ts
- src/specBuilder/line/lineMarkUtils.ts
- src/specBuilder/line/lineSpecBuilder.ts
- src/specBuilder/marks/markUtils.test.ts
- src/specBuilder/marks/markUtils.ts
- src/specBuilder/scatter/scatterMarkUtils.test.ts
- src/specBuilder/scatter/scatterMarkUtils.ts
- src/specBuilder/scatter/scatterSpecBuilder.test.ts
- src/specBuilder/scatter/scatterSpecBuilder.ts
- src/specBuilder/signal/signalSpecBuilder.test.ts
- src/specBuilder/signal/signalSpecBuilder.ts
- src/stories/components/ChartTooltip/ChartTooltip.story.tsx
- src/types/Chart.ts
- `excludeDataKey` prop added to `ChartTooltip`
-  Story demonstrating `excludeDataKey` use
-  Disable interaction, voronoi calculation, and tooltip display for data points where `excludeDataKey` is truthy
[AN-344693](https://jira.corp.adobe.com/browse/AN-344693) (Internal)
> Ability to disable tooltip for chart data based on key

- src/components/Trendline/Trendline.tsx
- src/specBuilder/trendline/trendlineDataUtils.test.ts
- src/specBuilder/trendline/trendlineDataUtils.ts
- src/stories/components/Trendline/Trendline.story.tsx
- src/types/Chart.ts
- Adds `excludeDataKey` prop to `Trendline` component. Any points in the chart data where the `excludeDataKey` is truthy will not be included in the trendline calculation.
[AN-344696](https://jira.corp.adobe.com/browse/AN-344696) (Internal)
- Unit tests in `trendlineDataUtils.test.ts`
- See story `rsc-trendline--exclude-series-from-trendline`
> Ability to exclude data points from trendline calculation

- .storybook/preview.tsx
- src/Chart.css
- src/Chart.tsx
- src/RscChart.tsx
- src/hooks/useChartHeight.tsx
- src/hooks/useResizeObserver.tsx
- src/stories/Chart.story.tsx
- src/stories/Chart.test.tsx
- src/types/Chart.ts
- src/utils/markClickUtils.ts
- Support percentage based heights
- Support min/max heights
- Percentage based heights will be updated on container resize
Closes #216 
Allows Charts to fill all or a percentage of the available vertical space
- Tested with new story in storybook
- linked package to my team's implementation and verified it works with quarry/dashboard widgets
https://github.com/adobe/react-spectrum-charts/assets/12468946/d65d38c5-7644-421e-a3e0-c4a9f650ba94
> feat: adds support for percentage based height

- package.json
Added 'main' field to package.json since Jest 26.x doesn't understand how to use 'module', 'browser', or 'exports' fields when this is a dependency of another package being tested.
> Add 'main' field for compatibility with Jest 26.x

- src/types/Chart.ts
This PR fixes the error `A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.` described in the issue https://github.com/adobe/react-spectrum-charts/issues/272. See "possible solution" in the issue for more details.
https://github.com/adobe/react-spectrum-charts/issues/272
> Fix the type error causing build failure in the destination package

- src/stories/components/Axis/Axis.story.tsx
- src/stories/components/Axis/Axis.test.tsx
- src/types/Chart.ts
Allow multi-line axis titles by supplying and array of strings. Each string in the array will render on a new line.
https://github.com/adobe/react-spectrum-charts/issues/269
Axis > MultilineTitle
> feat: support multi-line axis titles

- src/RscChart.tsx
- src/constants.ts
- src/hooks/useTooltips.tsx
- src/stories/components/ChartTooltip/HighlightBy.story.tsx
- src/stories/components/ChartTooltip/HighlightBy.test.tsx
- src/types/Chart.ts
This add `rscGroupData` as an available key to the tooltip if you are using `highlightBy`. This makes it possible to get all the data for all highlighted points, not just the hovered point.
https://github.com/adobe/react-spectrum-charts/issues/238
ChatTooltip > HighlightBy > GroupData
> feat: add group data to datum for tooltip when using highlightBy

- src/specBuilder/legend/legendHighlightUtils.test.ts
- src/specBuilder/legend/legendHighlightUtils.ts
- src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.story.tsx
- src/test-utils/customQueries.ts
- src/types/Chart.ts
A while ago we updated the highlight logic so that `opacity` is used to highlight and `stroke-opacity` and `fill-opacity` are used to set the static opacity values. This update didn't make it all the way down to legend highlight utils. This PR gets that up to date and a couple other house cleaning items.
> chore: clean up the legend highlight logic

- src/hooks/useChartHeight.tsx
- src/hooks/useChartWidth.tsx
Vega has performance issues if height/width contain decimals. This applies a `Math.round` so we only ever use integers.
Also fixed an issue where min/max values were being applied to static widths and heights. Static widths and heights should not respect min/max values.
https://github.com/adobe/react-spectrum-charts/issues/288
> Width height integers

- src/specBuilder/trendlineAnnotation/trendlineAnnotationUtils.ts
Trendline annotations should not be interactive. This means that hovering them should not interrupt tooltips. This fixes that.
https://github.com/adobe/react-spectrum-charts/assets/40001449/960dd7fd-2e49-48d5-94ed-f7fa7db31150
> fix: trendline annotations should not be interactive

- src/RscChart.tsx
- src/hooks/usePopovers.tsx
- src/stories/components/ChartPopover/ChartPopover.story.tsx
- src/stories/components/ChartPopover/ChartPopover.test.tsx
- src/types/Chart.ts
Add more props to control the size of ChartPopover.
* `minWidth`
* `maxWidth`
* `height`
* `minHeight`
* `maxHeight`
`width` now supports `'auto'`
Better layout control of popovers
ChartPopover > Size
ChartPopover > MinWidth
> feat: add size props to chartPopover

- src/specBuilder/legend/legendSpecBuilder.test.ts
- src/specBuilder/legend/legendUtils.test.ts
- src/specBuilder/legend/legendUtils.ts
- src/specBuilder/signal/signalSpecBuilder.test.ts
- src/specBuilder/signal/signalSpecBuilder.ts
get hide/show working with legend keys
> fix: hideShow support for legend keys

- package.json
- yarn.lock
Move @adobe/react-spectrum from dependencies to devDependencies
https://github.com/adobe/react-spectrum-charts/issues/286
Since `@adobe/react-spectrum` is in peerDependencies, it should not be in dependencies.
Add it to devDependencies for developing
Tested locally, story book can run as expected.
> Move @adobe/react-spectrum from dependencies to devDependencies

- src/RscChart.tsx
- src/hooks/usePopovers.tsx
- src/stories/components/ChartPopover/ChartPopover.story.tsx
- src/stories/components/ChartPopover/ChartPopover.test.tsx
- src/types/Chart.ts
- src/utils/markClickUtils.ts
Add `onOpenChange` to `ChartPopover`. This will allow users to trigger side effects when the chartpopover opens of closes.
ChartPopover > OnOpenChange
https://github.com/adobe/react-spectrum-charts/assets/40001449/3a0b4a1c-afd6-40c8-963e-397fd6c85bf0
> feat: add onOpenChange to popover

- src/constants.ts
- src/specBuilder/bar/barTestUtils.ts
- src/specBuilder/bar/barUtils.test.ts
- src/specBuilder/bar/barUtils.ts
- src/specBuilder/donut/donutSpecBuilder.test.ts
- src/specBuilder/donut/donutSpecBuilder.ts
- src/specBuilder/donut/donutTestUtils.ts
- src/specBuilder/donut/donutUtils.test.ts
- src/specBuilder/donut/donutUtils.ts
- src/specBuilder/marks/markUtils.test.ts
- src/specBuilder/marks/markUtils.ts
- src/stories/components/Donut/Donut.story.tsx
- src/stories/components/Donut/data.ts
Move some stuff to make it more reusable.
Update opacity rules to account for all highlight conditions.
Remove a bunch of inconsequential tests.
Refactor how data is passed around so it matches existing patterns.
Fix hardcoded `id` instead of using `color` field.
https://github.com/adobe/react-spectrum-charts/issues/218
Donut is still in `alpha`. This is the initial work for getting donut ready to move out of alpha.
Added tests, existing ones are passing.
> refactor: initial work to productionize donut

- src/VegaChart.tsx
- src/alpha/components/Donut/Donut.tsx
- src/alpha/components/SegmentLabel/SegmentLabel.tsx
- src/alpha/components/SegmentLabel/index.ts
- src/alpha/components/index.ts
- src/constants.ts
- src/specBuilder/donut/donutSpecBuilder.test.ts
- src/specBuilder/donut/donutSpecBuilder.ts
- src/specBuilder/donut/donutSummaryUtils.ts
- src/specBuilder/donut/donutTestUtils.ts
- src/specBuilder/donut/donutUtils.ts
- src/specBuilder/donut/segmentLabelUtils.test.tsx
- src/specBuilder/donut/segmentLabelUtils.ts
- src/stories/components/Donut/Donut.story.tsx
- src/stories/components/SegmentLabel/SegmentLabel.story.tsx
- src/stories/components/SegmentLabel/SegmentLabel.test.tsx
- src/types/Chart.ts
- src/types/specBuilderTypes.ts
- src/utils/utils.ts
Update the API, breaking out segment labels.
```
...
<Donut hasDirectLabels />
...
```
```
...
<Donut>
<SegmentLabel percent value valueFormat="shortNumber" />
</Donut>
...
```
New API gives far more control.
New support for:
* display or hide percent
* display or hide value
* value number format
* key in the data to use for the label
https://github.com/adobe/react-spectrum-charts/issues/218
Donut > SegmentLabel
> Donut segment label

- src/specBuilder/donut/segmentLabelUtils.test.tsx
- src/specBuilder/donut/segmentLabelUtils.ts
Update the segment label anchor position. The anchor used to be the left or right side in between the label and the value. Now it is based on the quadrant. For example: If the segment label is in the top left, it's anchor is the bottom right.
https://github.com/adobe/react-spectrum-charts/issues/218
It's subtle but notice how the spacing between the donut and the summary label is now more consistent (always 6px)
Donut > SegmentLabels
> feat: update text anchor for segment labels

- src/specBuilder/donut/donutSummaryUtils.test.tsx
- src/specBuilder/donut/donutSummaryUtils.ts
- src/stories/components/DonutSummary/DonutSummary.story.tsx
- src/stories/components/DonutSummary/DonutSummary.test.tsx
Center the donut summary value when there isn't a label.
#218 
Donut > DonutSummary > NoLabel
Was:
Is:
> feat: center donut summary without label

- src/specBuilder/donut/donutSummaryUtils.ts
- src/specBuilder/donut/segmentLabelUtils.ts
- src/utils/utils.ts
We were using referential equality to verify that the component is our `SegmentLabel` and/or `DonutSummary` components. This doesn't work for components imported from RC because the code will be verifying the `SegmentLabel` is the exact same component as exists in the standard export but users have to import `SegmentLabel` from `rc` so they are not referentially equal.
> fix: use displayName to check component type

- src/components/Line/Line.tsx
- src/constants.ts
- src/specBuilder/chartTooltip/chartTooltipUtils.test.ts
- src/specBuilder/chartTooltip/chartTooltipUtils.ts
- src/specBuilder/line/lineMarkUtils.test.ts
- src/specBuilder/line/lineMarkUtils.ts
- src/specBuilder/line/lineSpecBuilder.test.ts
- src/specBuilder/line/lineSpecBuilder.ts
- src/specBuilder/line/lineUtils.ts
- src/specBuilder/marks/markUtils.ts
- src/stories/components/Line/Line.story.tsx
- src/stories/components/Line/Line.test.tsx
- src/types/Chart.ts
- src/types/specBuilderTypes.ts
Add item interaction mode for `Line` that triggers tooltip when hovering over a particular area near points on the line
Voronoi method for tooltips on `Line` does not allow interaction with elements behind the line. `item` interaction mode allows for more precise interactions with the points on the `Line` and allows interaction with elements behind it.
Passed existing tests
Added tests to cover changes
> feat: Add item interaction mode for line

- .github/workflows/pr-sonar-new.yml
> test: download stuff twice

- .github/workflows/pr-sonar.yml
> chore: add comments

- src/expressionFunctions.test.ts
- src/expressionFunctions.ts
- src/specBuilder/axis/axisLabelUtils.test.ts
- src/specBuilder/axis/axisLabelUtils.ts
- src/stories/components/Axis/Axis.test.tsx
Add the ability to display duration in minute format `mm:ss` (previously only hour was supported `HH:mm:ss`).
Requested by users
> feat: minute duration axis labels

- src/specBuilder/bar/barSpecBuilder.test.ts
- src/specBuilder/bar/barSpecBuilder.ts
- src/specBuilder/bar/barUtils.test.ts
- src/specBuilder/bar/barUtils.ts
- src/stories/components/ChartPopover/ChartPopover.story.tsx
- src/stories/components/ChartPopover/ChartPopover.test.tsx
Adds a selection ring for bar charts when highlighting by dimension
When highlighting by dimension, instead of changing the stoke width and color for the bar that was selected, a new selection ring will appear that circles the entire dimension selected.
#374
> feat: bar dimension selection ring

- .github/workflows/pr-build.yml
- .gitignore
- package.json
- scripts/runSonarCloud.js
- src/specBuilder/bar/barUtils.ts
- yarn.lock
> Sonar script

- src/components/Bar/Bar.tsx
- src/specBuilder/bar/barSpecBuilder.ts
- src/specBuilder/bar/barUtils.test.ts
- src/specBuilder/bar/barUtils.ts
- src/stories/components/Combo/Combo.story.tsx
- src/stories/components/Combo/Combo.test.tsx
- src/stories/data/data.ts
- src/types/Chart.ts
Support custom axis for `Bar` chart. This allows correctly rendering axes when `Line` chart has larger scale than `Bar` chart in `Combo` chart
```jsx
<Combo dimension="datetime">
<Axis position="left" name="people" title="People" />
<Axis position="right" name="total" title="Total" />
<Bar metric="people" metricAxis="people" />
<Line metric="total" metricAxis="total" />
</Combo>
```
Support dual axes with larger scale for `Line` in `Combo` chart
Passed existing tests
Updated tests to cover changes
<div>
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</div>
> feat: Support custom axis for Bar chart

- src/specBuilder/axis/axisReferenceLineUtils.test.ts
- src/specBuilder/axis/axisReferenceLineUtils.ts
- src/specBuilder/axis/axisSpecBuilder.test.ts
- src/specBuilder/axis/axisSpecBuilder.ts
- src/specBuilder/axis/axisTestUtils.ts
- src/specBuilder/axis/axisUtils.test.ts
- src/stories/ChartExamples.test.tsx
- src/stories/components/Axis/AxisReferenceLine.story.tsx
- src/stories/components/Axis/AxisReferenceLine.test.tsx
- src/stories/components/Bar/ReferenceLineBar.test.tsx
- src/types/Chart.ts
- src/types/specBuilderTypes.ts
Add prop to control the color of the reference line.
> feat: set reference line color

- package.json
- src/constants.ts
- src/specBuilder/area/areaSpecBuilder.test.ts
- src/specBuilder/line/lineSpecBuilder.test.ts
- src/specBuilder/scale/scaleSpecBuilder.test.ts
- src/stories/ChartExamples/FeatureMatrix/FeatureMatrix.test.tsx
- src/stories/components/Axis/Axis.story.tsx
- src/stories/components/Axis/Axis.test.tsx
Padding existed on linear dimension axes but it was misleading and identified as a design bug. This removes that padding.
Existing padding was misleading on continuous data
Existing tests pass
Before:
After:
> feat: remove 32 padding on linear dimension scales

- src/components/ChartPopover/ChartPopover.tsx
- src/specBuilder/bar/barSpecBuilder.test.ts
- src/specBuilder/chartPopover/chartPopoverUtils.test.ts
- src/specBuilder/chartPopover/chartPopoverUtils.ts
- src/specBuilder/line/lineMarkUtils.test.ts
- src/specBuilder/line/lineMarkUtils.ts
- src/specBuilder/line/linePointUtils.test.ts
- src/specBuilder/line/linePointUtils.ts
- src/specBuilder/line/lineSpecBuilder.ts
- src/stories/ChartExamples.test.tsx
- src/stories/components/ChartPopover/ChartPopover.test.tsx
- src/stories/components/ChartTooltip/ChartTooltip.test.tsx
- src/stories/components/ChartTooltip/HighlightBy.test.tsx
- src/stories/components/Line/Line.test.tsx
Adds selection highlight support to Line charts
#374
> feat: line selection highlighting

- src/specBuilder/area/areaSpecBuilder.test.ts
- src/specBuilder/area/areaUtils.test.ts
- src/specBuilder/area/areaUtils.ts
- src/specBuilder/axis/axisTestUtils.ts
- src/specBuilder/axis/axisUtils.ts
- src/specBuilder/bar/barAnnotationUtils.ts
- src/specBuilder/bar/barSpecBuilder.test.ts
- src/specBuilder/bar/stackedBarUtils.test.ts
- src/specBuilder/bar/stackedBarUtils.ts
- src/specBuilder/donut/donutUtils.ts
- src/specBuilder/line/lineMarkUtils.test.ts
- src/specBuilder/line/lineMarkUtils.ts
- src/specBuilder/line/linePointUtils.ts
- src/specBuilder/line/lineSpecBuilder.test.ts
- src/specBuilder/marks/markUtils.ts
- src/specBuilder/metricRange/metricRangeUtils.test.ts
- src/specBuilder/scatter/scatterMarkUtils.ts
- src/specBuilder/trendlineAnnotation/trendlineAnnotationUtils.ts
Fix accessibility issue: `<svg> elements with an img role must have an alternative text`
https://github.com/adobe/react-spectrum-charts/issues/474
AEP- Sky Kraken team has using Basic bar, Line, Donut chart to render dashboards. (Area, Scatter, BigNumber might be in the future.) We got accessibility issue tickets like: [PLAT-182431](https://jira.corp.adobe.com/browse/PLAT-182431) and [PLAT-188199](https://jira.corp.adobe.com/browse/PLAT-188199) that complains `aria-label`, which is also applicable for RSC charts.
In this PR, I covered the charts that we are using and going to use.
Verified on preview story book, there is no `<svg> elements with an img role must have an alternative text` issue from `axe DevTools` for related chart types.
> Fix accessibility issue: <svg> elements with an img role must have an alternative text

- src/VegaChart.tsx
- src/expressionFunctions.test.ts
- src/expressionFunctions.ts
- src/specBuilder/axis/axisLabelUtils.ts
- src/specBuilder/textUtils.test.ts
- src/specBuilder/textUtils.ts
- src/stories/components/Axis/Axis.story.tsx
- src/types/Chart.ts
Introduces advanced configuration options for currency formatting on the axis.
- **`currencyLocale`**:  
Allows you to specify a locale string to determine the **positioning** and **spacing** of the currency format.  
Example:  
- `"en-US"`: `$100.00`  
- `"de-DE"` (positioning based on German locale): `100.00 $`  
- **`currencyCode`**:  
Lets you override the currency symbol from the current chart locale by specifying a currency code string.  
Example:  
- With currencyCode `"JPY"` using the above example:  
- `"de-DE"`: `100.00 ¥` or `100.00 JPY` (depending on how the currency code is supported in the `currencyLocale`)  
Will be done after merge
> feat: added advanced currency locale configuration

- src/themes/spectrumTheme.ts
We don't really want a label limit for the y axis. Causes unexpected behavior.
> fix: remove config for axis label limit

- src/specBuilder/bullet/bulletMarkUtils.test.ts
- src/specBuilder/bullet/bulletMarkUtils.ts
- src/stories/components/Bullet/Bullet.story.tsx
- src/stories/components/Bullet/data.ts
- src/types/Chart.ts
This PR introduces enhancements to the Bullet Chart by adding:
- Configurable number formatting (numberFormat), to specify how metric and target values are displayed using d3-format specifiers.
- Optional target and target value labels (showTarget, showTargetValue), to display the target line and its corresponding label.
These improvements provide flexibility in visualizing progress metrics while maintaining consistency with other charting components.
SCRUM-18 and SCRUM-25
This change is required to complete use case B and E.
- Added tests for numberFormat handling (e.g., $,.2f, .2s, ,.0%, etc.).
- Validated that showTarget and showTargetValue properly control visibility.
- Ensured getBulletMarks correctly generates the expected marks based on props.
- Verified UI updates in Storybook.
> Enhance bullet chart with configurable number formatting and optional target labels

- src/specBuilder/bullet/bulletMarkUtils.test.ts
- src/specBuilder/bullet/bulletMarkUtils.ts
- src/specBuilder/bullet/bulletSpecBuilder.ts
This PR refactors the Bullet chart’s getBulletScales and getBulletSignals functions to use the produce pattern from Immer. The refactored versions are now named addScales and addSignals and follow the same structure as other chart components (e.g., Bar, Donut).
General refactoring.
- Aligns Bullet chart logic with the rest of the chart implementations.
- Enables a standardized, immutable update pattern via produce.
- Updated the Bullet unit tests to pass the additional parameter ([]) required by the produce functions.
- Verified that Bullet renders correctly in Storybook and behaves as expected with both default and custom props.
- Ran the full test suite to confirm no regressions across other parts of the codebase.
> Scrum 35/refactor/bullet scales and signals produce

- src/specBuilder/bullet/bulletMarkUtils.test.ts
- src/specBuilder/bullet/bulletMarkUtils.ts
- src/specBuilder/bullet/bulletSpecBuilder.ts
Refactors the `getBulletMarks` logic to use produce and renames it to `addMarks` to align with the naming and structural conventions used in other chart spec builders (e.g., `addScales`, `addSignals`, `addData`). The new implementation pushes a single `GroupMark` into the marks array immutably.
General refactoring.
This change is part of a broader refactor to bring the Bullet chart implementation in line with other existing charts like Bar and Axis. Using `produce`:
- Improves code clarity and immutability.
- Aligns with consistent patterns used across the project.
- Makes future mark additions easier to integrate into the Bullet chart.
- Updated and ran all existing unit tests for Bullet marks.
- Confirmed expected structure and behavior by inspecting the returned GroupMark and …
> Scrum 39/refactor/bullet marks produce

- packages/themes/package.json
- packages/vega-spec-builder/package.json
- yarn.lock
Adding vega as a dependency of themes. Build was 4+MB since it was including vega in the final build.
> build: update dependencies to fix themes build size

- packages/react-spectrum-charts/src/stories/components/Bar/ReferenceLineBar.story.tsx
- packages/react-spectrum-charts/src/stories/components/Bar/ReferenceLineBar.test.tsx
- packages/vega-spec-builder/src/axis/axisReferenceLineUtils.test.ts
- packages/vega-spec-builder/src/axis/axisReferenceLineUtils.ts
- packages/vega-spec-builder/src/types/axis/referenceLineSpec.types.ts
Support line type on the ReferenceLine component
This PR adds support for different line types on ReferenceLine components. Users can now specify various line styles (solid, dashed, dotted, etc.) for reference lines to improve visual distinction and customization options.
AN-389085
Reference lines are commonly used to highlight important thresholds or benchmarks in charts. Currently, all reference lines render as solid lines, which limits visual customization and can make it difficult to distinguish between multiple reference lines or different types of reference lines (e.g., target vs. average). Adding line type support allows users to:
- Use different patterns to distinguish multiple reference lines
- Improve overall chart readability and visual hierarchy
Unit Tests
- Added …
> Support line type on ReferenceLine

- .storybook/preview.tsx
- .storybook/storybook.css
- packages/react-spectrum-charts/src/stories/Chart.story.tsx
- packages/react-spectrum-charts/src/stories/Chart.test.tsx
- packages/react-spectrum-charts/src/stories/ChartDynamicHeightBarStory.tsx
Storybook stories used to be the height of the window. This made the docs page look odd since all the stories were too tall.
Tried fixing this in the past but had issues were the storybook preview window was white regardless of light or dark mode.
1. Made the height the story be only as tall as it needs to be.
2. Made the storybook preview background match light vs dark mode.
All tests are passing
Before:
After:
> Fix storybook size

- packages/constants/constants.ts
- packages/react-spectrum-charts/src/stories/Chart.test.tsx
- packages/react-spectrum-charts/src/stories/components/Area/Area.test.tsx
- packages/react-spectrum-charts/src/stories/components/ChartPopover/ChartPopover.test.tsx
- packages/react-spectrum-charts/src/stories/components/ChartTooltip/ChartTooltip.test.tsx
- packages/react-spectrum-charts/src/stories/components/ChartTooltip/HighlightBy.test.tsx
- packages/react-spectrum-charts/src/stories/components/Legend/Legend.test.tsx
- packages/react-spectrum-charts/src/stories/components/Legend/LegendHideShow.test.tsx
- packages/react-spectrum-charts/src/stories/components/Legend/LegendHighlight.test.tsx
- packages/react-spectrum-charts/src/stories/components/Line/Line.test.tsx
- packages/react-spectrum-charts/src/stories/components/Scatter/Scatter.test.tsx
- packages/react-spectrum-charts/src/stories/components/Trendline/Trendline.test.tsx
- packages/vega-spec-builder/src/area/areaUtils.ts
- packages/vega-spec-builder/src/axis/axisSpecBuilder.test.ts
- packages/vega-spec-builder/src/axis/axisSpecBuilder.ts
- packages/vega-spec-builder/src/bar/dodgedBarUtils.test.ts
- packages/vega-spec-builder/src/chartTooltip/chartTooltipUtils.ts
- packages/vega-spec-builder/src/legend/legendHighlightUtils.test.ts
- packages/vega-spec-builder/src/legend/legendHighlightUtils.ts
- packages/vega-spec-builder/src/legend/legendTestUtils.ts
- packages/vega-spec-builder/src/legend/legendUtils.ts
- packages/vega-spec-builder/src/line/lineMarkUtils.test.ts
- packages/vega-spec-builder/src/line/lineMarkUtils.ts
- packages/vega-spec-builder/src/marks/markUtils.test.ts
- packages/vega-spec-builder/src/marks/markUtils.ts
- packages/vega-spec-builder/src/scatter/scatterMarkUtils.ts
- packages/vega-spec-builder/src/scatterPath/scatterPathUtils.ts
Switch HIGHLIGHT_CONTRAST_RATIO to FADE_FACTOR.
Easier to use `0.2` everywhere instead of `1 / 5`
> refactor: change HILIGHT_CONTRAST_RATIO to FADE_FACTOR
